Disabled validation because the schema perms are broken on Traivs?
```
error: error validating "export-persistentvolumeclaim.yaml": error validating data: open /home/travis/.kube/schema/v0.0.0-master+a57c33bd28173/api/v1/schema.json: permission denied; if you choose to ignore these errors, turn validation off with --validate=false
```